-- local function my_on_attach(bufnr)
--     local api = require "nvim-tree.api"
--
--     local function opts(desc)
--         return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
--     end
--
--     -- default mappings
--     api.config.mappings.default_on_attach(bufnr)
--
--     -- custom mappings
--     vim.keymap.set("n", "?", api.tree.toggle_help, opts "Help")
--     vim.keymap.set("n", "l", api.node.open.edit, opts "Open")
--     vim.keymap.set("n", "h", api.node.navigate.parent_close, opts "Close directory")
--
--     vim.keymap.set("n", "<C-K>", "<cmd>:TmuxNavigateUp<cr>", opts "Close directory")
--     vim.keymap.set("n", "<Enter>", api.node.open.no_window_picker, opts "Open no picker")
-- end
--
-- local tree = require "nvim-tree"
--
-- local config = {
--     on_attach = my_on_attach,
--     -- hijack_directories = {
--     --     enable = false,
--     -- },
--     -- update_cwd = true,
--     renderer = {
--         -- root_folder_label = ":~:s?$?:t",
--         root_folder_label = ":t",
--         full_name = false,
--         highlight_opened_files = "name", -- Не выделять открытые файлы
--         -- indent_markers = {
--         --     enable = false,
--         --     icons = {
--         --         corner = "└ ",
--         --         edge = "│ ",
--         --         none = "  ",
--         --     },
--         -- },
--         -- icons = {
--         --     webdev_colors = true,
--         --     git_placement = "before",
--         --     padding = " ",
--         --     symlink_arrow = " ➛ ",
--         --     show = {
--         --         file = true,
--         --         folder = true,
--         --         folder_arrow = true,
--         --         git = true,
--         --     },
--         --     glyphs = {
--         --         default = "",
--         --         symlink = "",
--         --         folder = {
--         --             default = "",
--         --             open = "",
--         --             empty = "",
--         --             empty_open = "",
--         --             symlink = "",
--         --             symlink_open = "",
--         --         },
--         --         git = {
--         --             unstaged = "",
--         --             staged = "S",
--         --             unmerged = "",
--         --             renamed = "➜",
--         --             untracked = "U",
--         --             deleted = "",
--         --             ignored = "◌",
--         --         },
--         --     },
--         -- },
--     },
--     diagnostics = {
--         enable = true,
--     },
--     -- update_focused_file = {
--     --     enable = true,
--     --     update_cwd = true,
--     --     ignore_list = {},
--     -- },
--     git = {
--         enable = true,
--         ignore = true,
--         timeout = 500,
--     },
--     view = {
--         side = "left",
--         adaptive_size = true,
--         relativenumber = true,
--         number = true,
--     },
-- }
--
-- tree.setup(config)
